name: Go build and release

on:
  push:
    branches: [ "main" ]
  tags:
    - '*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o pretend-linux-amd64
        GOOS=darwin GOARCH=amd64 go build -v -o pretend-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -v -o pretend-darwin-arm64
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Create Github Release and updaload assets
      uses: softprops/action-gh-release@v2
      with:
        files:
          pretend-linux-amd64
          pretend-darwin-amd64
          pretend-darwin-arm64
      env:
        GITHUB_TOKEN: ${{secrets.GHACTIONS_TOKEN}}
